/*
 * generated by Xtext 2.17.0
 */
package org.xtext.mdsd_individual.ard.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class ArdlersUiModule extends AbstractArdlersUiModule {
}
