/*
 * generated by Xtext 2.17.0
 */
package org.xtext.mdsd_individual.ard


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ArdlersStandaloneSetup extends ArdlersStandaloneSetupGenerated {

	def static void doSetup() {
		new ArdlersStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
